default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= Rails.application.credentials.database[:name] %>
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  timeout: 5000

development:
  primary:
    <<: *default
  primary_replica:
    <<: *default
    replica: true

test:
  primary:
    <<: *default
  primary_replica:
    <<: *default
    replica: true

production:
  primary:
    <<: *default
  primary_replica:
    <<: *default
    replica: true
